### ISSUE TITLE
StrCat to string_view Casting Error (?)

### ISSUE THREAD

**Issue by orhanuysal-google** [googleinterns/zetasql-lint#12]
CheckLineLength output was strange(random characters), so i tracked the error and found that:
For the code:
```
#include <iostream>
#include <string>
#include "absl/strings/str_cat.h"
#include "absl/strings/string_view.h"

int main() {
  absl::string_view sd =
      absl::StrCat("Lines should be <= ", 3, " characters long");
  std::cout << sd << std::endl;

  std::cout << absl::StrCat("Lines should be <= ", 3, " characters long")
            << std::endl;
  return 0;
}
```
The output is:
PV��Z<= 3 characters long
Lines should be <= 3 characters long

When you use ``std::string`` the output is fine.

# EDIT
I now understand the bug, we can't store LintResult like a normal object (because it contains pointers (absl::string_view)). So either messages shouldn't be created inside check, or result should be printed immediately after check (Tests will also print results in this case)

The Code:
```
#include <iostream>
#include <string>
#include "absl/strings/str_cat.h"
#include "absl/strings/string_view.h"

class LintResult {
 public:
  std::vector<absl::string_view> GetMessages() { return messages; }
  void add(absl::string_view mess) {
    std::cout << mess << std::endl;
    messages.push_back(absl::string_view(mess));
  }
  void Print() {
    for (absl::string_view me : messages)
        std::cout << "the messeage is : " << me << std::endl;
  }

 private:
  std::vector<absl::string_view> messages;
};

LintResult lintCheck() {
    std::string s = absl::StrCat("Lines should be <= ", 3, " characters long");
    LintResult result;
    result.add(s);
    result.Print();
    return result;
}

int main() {
  LintResult result = lintCheck();
  result.Print();
  return 0;
}
```

Output:
Lines should be <= 3 characters long
the messeage is : Lines should be <= 3 characters long
the messeage is : С��[<= 3 characters long

We can convert the messages back to global (where it will be generated according to error type), and messages can also access config file to get info, or simply create new instance for each message for now(total memory shouldn't be too much)

**Comment by a-litvinov** [comment]
absl::string_view doesn't own the memory for the string, so here is what happens here:

absl::StrCat(...) - creates a temporary string
absl::string_view sd = ... - creates a string_view that points to the temp string
temp string goes out of scope, so string view is now pointing to the freed memory.

You should always use std::string to store the actual string. string_view is a light-weight pointer to the string that is cheap to pass to other functions as an argument.

**Comment by a-litvinov** [comment]
https://abseil.io/tips/1
